services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [mihovil]

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on: [db]
    networks: [mihovil]

  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ../.env
    volumes:
      - ../backend/app:/app/app
    ports:
      - "8000:8000"
    depends_on: [db]
    networks: [mihovil]

volumes:
  dbdata:

networks:
  mihovil:
